name: Deploy React TS

on:
  push:
    branches: ["develop"] # develop 브랜치에 푸시할 때
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build: # 1단계: 빌드 작업 추가
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build # 여기서 .ts가 .js로 변환됨
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist' # 빌드 결과물이 저장되는 폴더 (Vite 기준)

  deploy: # 2단계: 배포 작업
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
